package com.iyzico.challenge.integrator.dto;

public enum ErrorCode {
    NOT_AUTHORIZED,
    API_NOT_FOUND,
    INVALID_CREDENTIALS,
    INVALID_REQUEST,
    PAYMENT_EXCEPTION,

    USER_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    USERNAME_TAKEN_BY_ANOTHER_USER,

    UNEXPECTED_ERROR
}
